---------------------------------------------------------------------
-- Simple WISHBONE interconnect
--
-- Generated by wigen at Sun Dec  4 20:49:35 2016
--
-- Configuration:
--     Number of masters:     1
--     Number of slaves:      1
--     Master address width:  26
--     Slave address width:   8
--     Port size:             8
--     Port granularity:      8
--     Entity name:           papro_lpc
--     Pipelined arbiter:     no
--     Registered feedback:   no
--     Unsafe slave decoder:  no
--
-- Command line:
--     wigen -e papro_lpc 1 1 26 8 8 8
---------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;

entity papro_lpc is
    port(
        clk_i: in std_logic;
        rst_i: in std_logic;

        s0_cyc_i: in std_logic;
        s0_stb_i: in std_logic;
        s0_we_i: in std_logic;
        s0_ack_o: out std_logic;
        s0_adr_i: in std_logic_vector(25 downto 0);
        s0_dat_i: in std_logic_vector(7 downto 0);
        s0_dat_o: out std_logic_vector(7 downto 0);

        m0_cyc_o: out std_logic;
        m0_stb_o: out std_logic;
        m0_we_o: out std_logic;
        m0_ack_i: in std_logic;
        m0_adr_o: out std_logic_vector(7 downto 0);
        m0_dat_o: out std_logic_vector(7 downto 0);
        m0_dat_i: in std_logic_vector(7 downto 0)
    );
end entity;

architecture rtl of papro_lpc is

signal cyc_mux: std_logic;
signal stb_mux: std_logic;
signal we_mux: std_logic;
signal adr_mux: std_logic_vector(25 downto 0);
signal wdata_mux: std_logic_vector(7 downto 0);

signal ack_mux: std_logic;
signal rdata_mux: std_logic_vector(7 downto 0);

begin

-- MASTER->SLAVE MUX

cyc_mux<=s0_cyc_i;
stb_mux<=s0_stb_i;
we_mux<=s0_we_i;
adr_mux<=s0_adr_i;
wdata_mux<=s0_dat_i;

-- MASTER->SLAVE DEMUX

m0_cyc_o<=cyc_mux;
m0_stb_o<=stb_mux;
m0_we_o<=we_mux;
m0_adr_o<=adr_mux(m0_adr_o'range);
m0_dat_o<=wdata_mux;

-- SLAVE->MASTER MUX

ack_mux<=m0_ack_i;
rdata_mux<=m0_dat_i;

-- SLAVE->MASTER DEMUX

s0_ack_o<=ack_mux;
s0_dat_o<=rdata_mux;

end architecture;
